name: mma
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - conda=23.5.0
  - pip=23.0.1
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pip:
    - transformers==4.32.1
    - tokenizers==0.13.3
    - accelerate==0.20.3
    - huggingface-hub==0.16.4